=== zoek1211/secure-web-app/website/WEB-INF/users.dtd
<!ELEMENT users (user+)>
<!ELEMENT user (userid,name,password)>
<!ELEMENT userid (#PCDATA)>
<!ELEMENT password (#PCDATA)>
<!ELEMENT name (#PCDATA)>

=== zoek1211/secure-web-app/website/WEB-INF/users.xml
<!DOCTYPE users SYSTEM "users.dtd">
<users>
    <user>
        <userid>1</userid>
        <name>Esha</name>
        <password>123</password>
    </user>
    <user>
        <userid>2</userid>
        <name>Mumtaaz</name>
        <password>123</password>
    </user>
    <user>
        <userid>3</userid>
        <name>Shivraj</name>
        <password>123</password>
    </user>
    <user>
        <userid>4</userid>
        <name>Zoe</name>
        <password>123</password>
    </user>
   <user>
        <userid>5</userid>
        <name>Tarun</name>
        <password>123</password>
    </user>
</users>
